export const INTENT_KEYWORDS = {
  greeting: ['hello', 'helo', 'hi', 'hey', 'good morning', 'good afternoon', 'good evening', 'assalamu alaikum', 'salam', 'হ্যালো', 'হাই', 'সালাম'],
  gratitude: ['thank you', 'thanks', 'thx', 'thank u', 'much appreciated', 'dhonnobad', 'ধন্যবাদ'],
  goodbye: ['bye', 'goodbye', 'see you', 'take care', 'talk to you later', 'later', 'বিদায়', 'bye bye'],
  languageRequest: ['speak bangla', 'talk in bangla', 'reply in bangla', 'answer in bangla', 'speak in bangla', 'use bangla', 'বাংলায় কথা', 'বাংলায় কথা বলুন', 'বাংলায় কথা', 'বাংলায় কথা বলুন', 'বাংলায় reply', 'বাংলায় answer'],
  symptomDiscussion: [
    'fever',
    'headache',
    'cough',
    'cold',
    'flu',
    'sore throat',
    'pain',
    'ache',
    'nausea',
    'vomit',
    'diarrhea',
    'dizzy',
    'dizziness',
    'rash',
    'itching',
    'swelling',
    'shortness of breath',
    'breathing difficulty',
    'breathing problem',
    'chest pain',
    'palpitation',
    'fatigue',
    'weakness',
    'sick',
    'unwell',
    'feeling sick',
    'feeling ill',
    'not feeling well',
    'under the weather',
    'feverish',
    'stomach pain',
    'back pain',
    'body ache',
    'tooth pain',
    'ear pain',
    'eye pain',
  ],
  wellnessQuestion: ['sleep', 'insomnia', 'stress', 'anxiety', 'hydration', 'water', 'nutrition', 'diet', 'wellness', 'exercise', 'healthy', 'fatigue', 'tired', 'tiredness', 'routine', 'vitamin', 'immunity', 'mental health'],
  casualConversation: ['how are you', 'what can you do', 'who are you', 'tell me a joke', 'are you real', 'help me', 'thanks for helping', 'nice to meet you'],
}

export const FOLLOW_UP_HINTS = ['yes', 'yeah', 'yep', 'still', 'same', 'also', 'more', 'again', 'worse', 'better', 'little', 'bit', 'a bit', 'not much']
